### PR TITLE
added an EmailJS template that is fairly easy to use

### PR DESCRIPTION
**Pull request by BrendanGlancy**
image

### CODE REVIEW

**Comment by 1hanzla100** [comment]
@BrendanGlancy Need few improvements
1. onsubmit it should not reload page
2. it should not show native browser alert. you can try some popup alert
3. replace server info with env variables 
4. move this section to end of page (2nd last section).
5.  in `portfolio.js` add option to hide/show contact form.

**Comment by BrendanGlancy** [comment]
Okay, I will work on that in the coming days; thanks for the feedback. 
Would you like me to add a section in the readme about how to add the .env variables?

**Comment by BrendanGlancy** [comment]
@1hanzla100 I believe these are the changes you requested let me know if there's anything else.

### Success Alert
Screenshot from 2022-11-22 03-50-20

### Error Alert
image

**Comment by 1hanzla100** [comment]
@BrendanGlancy  I will Test it out and merge it to master after testing

**Pull request merged**
