### PR TITLE
Enhancement: Migration to TypeScript

### PR DESCRIPTION
**Pull request by vatsalsinghkv**
Solves #42 
- Added TypeScript types in `/types/`
- Added custom types for `portfolio.ts` in `types/section.ts`
- Migrated components from `.jsx` to `.tsx`
- Conditional rendering for resume button in `Greetings.tsx` (Optional to have resume button)
- Removed dependency `prop-types`
- Removed unused imports

### CODE REVIEW

**Comment by 1hanzla100** [comment]
@vatsalsinghkv I have added 2 comments. After fixing them. I will be merged.

**Comment by vatsalsinghkv** [comment]
> @vatsalsinghkv I have added 2 comments. After fixing them. I will be merged.

Sorry but I couldn't see any comments, could you guide me with this

**Comment by 1hanzla100** [comment]
Capture

**Comment by vatsalsinghkv** [comment]
@1hanzla100 Please take a look

**Pull request merged**
